from astral import LocationInfo
from astral.sun import sun
import datetime
import sys
import time

BEDTIME_SHUTDOWN_HOLD_TIME = 5
ABORT_BEDTIME_PROTOCOL_HOLD_TIME = 3

LONG_BREAK_HOLD_TIME = 2
QUICK_SPRINT_HOLD_TIME = 2
END_SESSION_HOLD_TIME = 2
DEMO_MODE_HOLD_TIME = 2
MAX_CLICK_TIME = 1.2

LONG_BREAK_LENGTH = 15 * 60
STANDARD_BREAK_LENGTH = 5 * 60
STANDARD_SPRINT_LENGTH = 25 * 60
QUICK_SPRINT_LENGTH = 15 * 60

FLICKERING_TOLERANCE = 0.2 # seconds // for button flickering



BEDTIME_COUNTDOWN_LENGTH = 20 * 60
DISPLAY_BEDTIME_LENGTH = 60 * 60

TIME_BEFORE_SUNRISE = 15 * 60
FAJR_PRAYER_LENGTH = 8 * 60
MORNING_BATHROOM_LENGTH = 7 * 60
REQUIRED_AMOUNT_OF_SLEEP = 8 * 60 * 60
BEDTIME_CLOSING_PRAYERS_LENGTH = 15 * 60

calculatedBedtimeBeforeSunrise = \
    TIME_BEFORE_SUNRISE + FAJR_PRAYER_LENGTH + MORNING_BATHROOM_LENGTH \
    + REQUIRED_AMOUNT_OF_SLEEP + BEDTIME_CLOSING_PRAYERS_LENGTH

DAILY_RECALCULATION_HOUR = 13 # o' clock

city = LocationInfo("London", "England", "Europe/London", 51.5, -0.116)
s = sun(city.observer, date=datetime.date(2009, 4, 22))


SPRINT_L_B = (0, 255, 0, 0.6)
BREAK_L_B = (255, 234, 0, 0.5)
INTERRUPTION_L_B = (255, 0, 0, 1)

DT = 1.0 / 50