from astral import LocationInfo
import datetime
import sys
import time
import pytz

BEDTIME_SHUTDOWN_HOLD_TIME = 5
ABORT_BEDTIME_PROTOCOL_HOLD_TIME = 3

LONG_BREAK_HOLD_TIME = 2
QUICK_SPRINT_HOLD_TIME = 2
END_SESSION_HOLD_TIME = 2
DEMO_MODE_HOLD_TIME = 2
MAX_CLICK_TIME = 1.2

END_STATS_DISPLAY_LENGTH = 5 # s
LONG_BREAK_LENGTH = 15 * 60 + END_STATS_DISPLAY_LENGTH + 1
STANDARD_BREAK_LENGTH = 1 * 60 + END_STATS_DISPLAY_LENGTH + 1
STANDARD_SPRINT_LENGTH = 25 * 60 + 1 
QUICK_SPRINT_LENGTH = 15 * 60 + 1

FLICKERING_TOLERANCE = 0.1 # seconds // for button flickering



BEDTIME_COUNTDOWN_LENGTH = 20 * 60 + 1
DISPLAY_BEDTIME_LENGTH = 60 * 60

TIME_BEFORE_SUNRISE = 15 * 60
FAJR_PRAYER_LENGTH = 8 * 60
MORNING_BATHROOM_LENGTH = 8 * 60
AWAKENING_PERIOD_LENGTH = 7 * 60
REQUIRED_AMOUNT_OF_SLEEP = 8 * 60 * 60
BEDTIME_CLOSING_PRAYERS_LENGTH = 15 * 60

CALCULATED_WAKE_TIME_BEFORE_SUNRISE = TIME_BEFORE_SUNRISE + FAJR_PRAYER_LENGTH + MORNING_BATHROOM_LENGTH + AWAKENING_PERIOD_LENGTH

CALCULATED_BEDTIME_BEFORE_SUNRISE = \
    CALCULATED_WAKE_TIME_BEFORE_SUNRISE \
    + REQUIRED_AMOUNT_OF_SLEEP + BEDTIME_CLOSING_PRAYERS_LENGTH

DAILY_RECALCULATION_HOUR = 13 # o' clock # must be some time around noon!

TZ = pytz.timezone("US/Eastern")
CITY = LocationInfo("Milton, WV", "United States", "US/Eastern", 38.435060, -82.192510)

MORNING_WAKE_EFFECT_LENGTH = AWAKENING_PERIOD_LENGTH

SPRINT_L_B = (0, 255, 0, 0.31)
BREAK_L_B = (255, 225, 0, 0.4)
INTERRUPTION_L_B = (255, 0, 0, 1)
MORNING_L_B = (255, 250, 209,1)

CLOCK_BRIGHTNESS = 7 # 0 min, max 7

DT = 1.0 / 50